/* Microchip Technology Inc. and its subsidiaries.  You may use this software 
 * and any derivatives exclusively with Microchip products. 
 * 
 * THIS SOFTWARE IS SUPPLIED BY MICROCHIP "AS IS".  NO WARRANTIES, WHETHER 
 * EXPRESS, IMPLIED OR STATUTORY, APPLY TO THIS SOFTWARE, INCLUDING ANY IMPLIED 
 * WARRANTIES OF NON-INFRINGEMENT, MERCHANTABILITY, AND FITNESS FOR A 
 * PARTICULAR PURPOSE, OR ITS INTERACTION WITH MICROCHIP PRODUCTS, COMBINATION 
 * WITH ANY OTHER PRODUCTS, OR USE IN ANY APPLICATION. 
 *
 * IN NO EVENT WILL MICROCHIP BE LIABLE FOR ANY INDIRECT, SPECIAL, PUNITIVE, 
 * INCIDENTAL OR CONSEQUENTIAL LOSS, DAMAGE, COST OR EXPENSE OF ANY KIND 
 * WHATSOEVER RELATED TO THE SOFTWARE, HOWEVER CAUSED, EVEN IF MICROCHIP HAS 
 * BEEN ADVISED OF THE POSSIBILITY OR THE DAMAGES ARE FORESEEABLE.  TO THE 
 * FULLEST EXTENT ALLOWED BY LAW, MICROCHIP'S TOTAL LIABILITY ON ALL CLAIMS 
 * IN ANY WAY RELATED TO THIS SOFTWARE WILL NOT EXCEED THE AMOUNT OF FEES, IF 
 * ANY, THAT YOU HAVE PAID DIRECTLY TO MICROCHIP FOR THIS SOFTWARE.
 *
 * MICROCHIP PROVIDES THIS SOFTWARE CONDITIONALLY UPON YOUR ACCEPTANCE OF THESE 
 * TERMS. 
 */

/*******************************************************************************
  This source file has NOT been generated by the MHC
 *******************************************************************************/

/* 
 * File:   
 * Author: 
 * Comments:
 * Revision history: 
 */

// *****************************************************************************
// *****************************************************************************
// Section: Included Files 
// *****************************************************************************
// *****************************************************************************

#include "PacketManip.h"

// *****************************************************************************
// *****************************************************************************
// Section: Global Data Definitions
// *****************************************************************************
// *****************************************************************************

//PACKETMANIP_DATA packetmanipData;

// *****************************************************************************
// *****************************************************************************
// Section: User Functions
// *****************************************************************************
// *****************************************************************************

// Comment a function definition and leverage automatic documentation 
/**
  <p><b>Function:</b></p>

  <p><b>Summary:</b></p>

  <p><b>Description:</b></p>

  <p><b>Remarks:</b></p>
 */
// TODO Insert function definitions (right here) to leverage live documentation


void concatenate3(char dest[21], char type[2], char typeNum[3], char one[2], char oneNum[3], char two[2], char twoNum[3] )
{
    int i = 0;
    
    for (i=0;i<2;i++)
    {
        dest[i] = type[i];
        
    }
    dest[i] = ':';
    i++;
    for (i=3;i<6;i++)
    {
        dest[i] = typeNum[i-3];
    }
    dest[i] = ',';
    i++;
    
    for (i=7;i<9;i++)
    {
        dest[i] = one[i-7];
        
    }
    dest[i] = ':';
    i++;
    for (i=10;i<13;i++)
    {
        dest[i] = oneNum[i-10];
    }
    dest[i] = ',';
    i++;
    
    for (i=14;i<16;i++)
    {
        dest[i] = two[i-14];
        
    }
    dest[i] = ':';
    i++;
    for (i=17;i<20;i++)
    {
        dest[i] = twoNum[i-17];
    }
    dest[20] = '\0';    
    
    /*
    Doesn't work:
    strcpy(dest,a);
    strcat(dest,b);
    */
}

void concatenate5(char dest[35], char type[2], char typeNum[3], char one[2], char oneNum[3], char two[2], char twoNum[3], char thr[2], char thrNum[3], char fou[2], char fouNum[3])
{
    int i = 0;
    
    for (i=0;i<2;i++)
    {
        dest[i] = type[i];
        
    }
    dest[i] = ':';
    i++;
    for (i=3;i<6;i++)
    {
        dest[i] = typeNum[i-3];
    }
    dest[i] = ',';
    i++;
    
    for (i=7;i<9;i++)
    {
        dest[i] = one[i-7];
        
    }
    dest[i] = ':';
    i++;
    for (i=10;i<13;i++)
    {
        dest[i] = oneNum[i-10];
    }
    dest[i] = ',';
    i++;
    
    for (i=14;i<16;i++)
    {
        dest[i] = two[i-14];
        
    }
    dest[i] = ':';
    i++;
    for (i=17;i<20;i++)
    {
        dest[i] = twoNum[i-17];
    }
    dest[i] = ',';
    i++;
    
    for (i=22;i<24;i++)
    {
        dest[i] = thr[i-22];        
    }
    dest[i] = ':';
    i++;
    for (i=25;i<28;i++)
    {
        dest[i] = thrNum[i-25];
    }
    dest[i] = ',';
    i++;
    
    for (i=29;i<31;i++)
    {
        dest[i] = fou[i-29];        
    }
    dest[i] = ':';
    i++;
    for (i=32;i<34;i++)
    {
        dest[i] = fouNum[i-32];
    }
    
    dest[34] = '\0';
}

void concatenate6(char dest[42], char type[2], char typeNum[3], char one[2], char oneNum[3], char two[2], char twoNum[3], char thr[2], char thrNum[3], char fou[2], char fouNum[3], char fiv[2], char fivNum[3])
{
    int i = 0;
    
    for (i=0;i<2;i++)
    {
        dest[i] = type[i];
        
    }
    dest[i] = ':';
    i++;
    for (i=3;i<6;i++)
    {
        dest[i] = typeNum[i-3];
    }
    dest[i] = ',';
    
    i++;
    for (i=7;i<9;i++)
    {
        dest[i] = one[i-7];
        
    }
    dest[i] = ':';
    i++;
    for (i=10;i<13;i++)
    {
        dest[i] = oneNum[i-10];
    }
    dest[i] = ',';
    i++;
    
    for (i=14;i<16;i++)
    {
        dest[i] = two[i-14];
        
    }
    dest[i] = ':';
    i++;
    for (i=17;i<20;i++)
    {
        dest[i] = twoNum[i-17];
    }
    dest[i] = ',';
    i++;
    
    for (i=21;i<23;i++)
    {
        dest[i] = thr[i-21];        
    }
    dest[i] = ':';
    i++;
    for (i=24;i<27;i++)
    {
        dest[i] = thrNum[i-24];
    }
    dest[i] = ',';
    i++;
    
    for (i=28;i<30;i++)
    {
        dest[i] = fou[i-28];        
    }
    dest[i] = ':';
    i++;
    for (i=31;i<34;i++)
    {
        dest[i] = fouNum[i-31];
    }
    dest[i] = ',';
    i++;
    
    for (i=35;i<37;i++)
    {
        dest[i] = fiv[i-35];        
    }
    dest[i] = ':';
    i++;
    for (i=38;i<41;i++)
    {
        dest[i] = fivNum[i-38];
    }
    
    dest[41] = '\0';
}

/*******************************************************************************
  Function:
    

  Summary:
     

  Description:
    Returns false if the packet:
       - Is not the correct length
       - Does not fit the below format (where N is a number and C is a char)
            CC:NNN,CC:NNN,CC:NNN,CC:NNN,CC:NNN,CC:NNN
            CC:NNN,CC:NNN,CC:NNN,CC:NNN,CC:NNN
            CC:NNN,CC:NNN,CC:NNN
       - The characters do not fit the bellow formats
            Error Packets
            ES:000,RM:000,NS:000,NR:000,NU:001
            EC:000,RM:000,NS:000,NR:000,NU:001
            EM:000,RM:000,NS:000,NR:000,NU:001
            EF:000,RM:000,NS:000,NR:000,NU:001

            Data Packet
            SR:111,RS:000,LS:000,FS:000,BS:000,NU:001
            CM:000,ME:000,NU:001
            MR:111,DA:000,NU:001
            FF:111,RF:000,LF:004,CF:001,NU:001

            ACK Packets
            AS:111,AN:008,NU:001
            AC:000,AN:008,NU:001
            AM:111,AN:008,NU:001
            AF:111,AN:008,NU:001

  Precondition:
    

  Parameters:
    None.

  Returns:
    Error code:
        0:
        1: 
        2: 

  Example:
    <code>
    
    </code>

  Remarks:
    
*/
int isValidPacket(char* packettocheck)
{
    int len = 0;
    while (packettocheck[len] != '\0')
    {
        len += 1;
    }
    //return len;
    //if (len == 41)// && len != 34 && len != 20)
    {
        // Bad length
      //  return 1;
    }
    int x;
    if (len == 20)
    {
        if (packettocheck[2] != ':' || packettocheck[6] != ','
                || packettocheck[9] != ':' || packettocheck[13] != ','
                || packettocheck[16] != ':')
            // Invalid delimeters
            return 2;
        if (isalpha(packettocheck[0]) == 0 || isalpha(packettocheck[1]) == 0 ||
                isdigit(packettocheck[3]) == 0 || isdigit(packettocheck[4]) == 0 ||
                isdigit(packettocheck[5]) == 0 ||
                isalpha(packettocheck[7]) == 0 || isalpha(packettocheck[8]) == 0 ||
                isdigit(packettocheck[10]) == 0 || isdigit(packettocheck[11]) == 0 ||
                isdigit(packettocheck[12]) == 0 ||
                isalpha(packettocheck[14]) == 0 || isalpha(packettocheck[15]) == 0 ||
                isdigit(packettocheck[17]) == 0 || isdigit(packettocheck[18]) == 0 ||
                isdigit(packettocheck[19]) == 0 )
            // Alpha/digit in wrong place
            return 3;
    }
    else if (len == 34)
    {
        if (packettocheck[2] != ':' || packettocheck[6] != ','
                || packettocheck[9] != ':' || packettocheck[13] != ','
                || packettocheck[16] != ':' || packettocheck[20] != ','
                || packettocheck[23] != ':' || packettocheck[27] != ','
                || packettocheck[30] != ':' )
            // Invalid delimeters
            return 2;
        if (isalpha(packettocheck[0]) == 0 || isalpha(packettocheck[1]) == 0 ||
                isdigit(packettocheck[3]) == 0 || isdigit(packettocheck[4]) == 0 ||
                isdigit(packettocheck[5]) == 0 ||
                isalpha(packettocheck[7]) == 0 || isalpha(packettocheck[8]) == 0 ||
                isdigit(packettocheck[10]) == 0 || isdigit(packettocheck[11]) == 0 ||
                isdigit(packettocheck[12]) == 0 ||
                isalpha(packettocheck[14]) == 0 || isalpha(packettocheck[15]) == 0 ||
                isdigit(packettocheck[17]) == 0 || isdigit(packettocheck[18]) == 0 ||
                isdigit(packettocheck[19]) == 0 ||
                isalpha(packettocheck[21]) == 0 || isalpha(packettocheck[22]) == 0 ||
                isdigit(packettocheck[24]) == 0 || isdigit(packettocheck[25]) == 0 ||
                isdigit(packettocheck[26]) == 0 ||
                isalpha(packettocheck[28]) == 0 || isalpha(packettocheck[29]) == 0 ||
                isdigit(packettocheck[31]) == 0 || isdigit(packettocheck[32]) == 0 ||
                isdigit(packettocheck[33]) == 0 )
            // Alpha/digit in wrong place
            return 3;
    }
    else if (len == 41)
    {
        if (packettocheck[2] != ':' || packettocheck[6] != ','
                || packettocheck[9] != ':' || packettocheck[13] != ','
                || packettocheck[16] != ':' || packettocheck[20] != ','
                || packettocheck[23] != ':' || packettocheck[27] != ','
                || packettocheck[30] != ':' || packettocheck[27] != ','
                || packettocheck[30] != ':' || packettocheck[27] != ',')
            // Invalid delimeters
            return 2;
        if (isalpha(packettocheck[0]) == 0 || isalpha(packettocheck[1]) == 0 ||
                isdigit(packettocheck[3]) == 0 || isdigit(packettocheck[4]) == 0 ||
                isdigit(packettocheck[5]) == 0 ||
                isalpha(packettocheck[7]) == 0 || isalpha(packettocheck[8]) == 0 ||
                isdigit(packettocheck[10]) == 0 || isdigit(packettocheck[11]) == 0 ||
                isdigit(packettocheck[12]) == 0 ||
                isalpha(packettocheck[14]) == 0 || isalpha(packettocheck[15]) == 0 ||
                isdigit(packettocheck[17]) == 0 || isdigit(packettocheck[18]) == 0 ||
                isdigit(packettocheck[19]) == 0 ||
                isalpha(packettocheck[21]) == 0 || isalpha(packettocheck[22]) == 0 ||
                isdigit(packettocheck[24]) == 0 || isdigit(packettocheck[25]) == 0 ||
                isdigit(packettocheck[26]) == 0 ||
                isalpha(packettocheck[28]) == 0 || isalpha(packettocheck[29]) == 0 ||
                isdigit(packettocheck[31]) == 0 || isdigit(packettocheck[32]) == 0 ||
                isdigit(packettocheck[33]) == 0 ||
                isalpha(packettocheck[35]) == 0 || isalpha(packettocheck[36]) == 0 ||
                isdigit(packettocheck[38]) == 0 || isdigit(packettocheck[39]) == 0 ||
                isdigit(packettocheck[40]) == 0 )
            // Alpha/digit in wrong place
            return 3;
    }
    switch(packettocheck[0])
    {
        case 'E':
            switch(packettocheck[1])
            {
                case 'S':
                    x=0; break;
                case 'C':
                    x=0; break;
                case 'M':
                    x=0; break;
                case 'F':
                    x=0; break;
                default:
                    x=4; break;
            }
            break;
        case 'S':
            x=0; break;
        case 'M':
            x=0; break;
        case 'C':
            x=0; break;
        case 'F':
            x=0; break;
        default: 
            x=4; break;
    }
    // If 4, invalid starter flag
    return x;                       
}
//returns true or false on whether the packet is a error packet
int isErrorPacket(char* packettocheck)
{
    int x = 0;
    if(packettocheck[0]=='E')
    {
        x = 1;
    }
    return x;
}

// Returns 1 if the packet is an ACK packet
int isAckPacket(char* packettocheck)
{
    int x = 0;
    if(packettocheck[0]=='A')
    {
        x = 1;
    }
    return x;
}


// Parses the last part of the packet to get the sequence number
// Returns int and changes dest
int getSequenceNumber(char dest[3], char* packettodostuff)
{
    int i=0;
    int j=0;
    int k=0;
    int r;
    char temp[3];
    while (packettodostuff[i] != '\0')
    {
        i=i+1;
    }
    i = i-3;
    for (j=0; j<3; j++)
    {
        temp[k] = packettodostuff[i];
        i=i+1;
        k=k+1;
    }
    dest[0] = temp[0];
    dest[1] = temp[1];
    dest[2] = temp[2];
    
    r = atoi(temp);
    return r;
}

void intTo3Char(char dest[3], int data)
{
    snprintf(dest, 4, "%03d", data);
}
